version: 2

aliases:

jobs:
  lint:
    docker:
    - image: circleci/node:8.11
    steps:
    - checkout
    - run: npm install
    - run: npm run lint
  test:
    docker:
    - image: circleci/node:8.11
    steps:
    - checkout
    - run: npm install
    - run: npm run test
  publish:
    docker:
    - image: circleci/node:8.11
    steps:
    - checkout
    - run: sudo npm install -g ci-publish
    - run: npm run ci-publish

workflows:
  version: 2
  test:
    jobs:
    - lint
    - test
  publish:
    jobs:
    - lint:
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v\d+\.\d+\.\d+(-\w+)?$/
    - test:
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v\d+\.\d+\.\d+(-\w+)?$/
    - publish:
        requires:
        - lint
        - test
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v\d+\.\d+\.\d+(-\w+)?$/
